const data = [
  {
    name: "Bamboo",
    fullnameTh: ["จณิสตา", "ตันศิริ"],
    fullnameEn: ["Janista", "Tansiri"],
    team: "NV",
    birthday: "2002-9-3",
    province: "Samut Prakan",
    favorite: ["Dogs", "Everything are yellow", "Healthy Snacks", "Earring"],
    hobby: [
      "Basketball",
      "Drawing",
      "Watching Comedian Show",
      "Cover Dance",
      "Cooking Dessert",
    ],
    img: "https://www.bnk48.com/data/Members/51/pro/l/20210602060249gtu589.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=51",
    follow: [
      "https://www.facebook.com/bnk48official.bamboo",
      "https://www.instagram.com/bamboo.bnk48office",
    ],
    graduated: false,
    keyword: ["bamboo", "Bamboo", "BAMBOO"],
    gen: 2,
  },
  {
    name: "Cherprang",
    fullnameTh: ["เฌอปราง", "อารีย์กุล"],
    fullnameEn: ["Cherprang", "Areekul"],
    team: "BIII",
    birthday: "1996-5-2",
    province: "Bangkok",
    favorite: ["Tofu", "Ice-cream"],
    hobby: ["Eating", "Sleeping", "Playing a game", "Cosplay"],
    img: "https://www.bnk48.com/data/Members/4/pro/l/20210602060307abe159.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=4",
    follow: [
      "https://www.facebook.com/bnk48official.cherprang",
      "https://www.instagram.com/cherprang.bnk48official",
    ],
    graduated: false,
    keyword: ["Cherprang", "cherprang", "CHERPRANG"],
    gen: 1,
  },
  {
    name: "Earn",
    fullnameTh: ["วชิราพร", "พัฒนพานิช"],
    fullnameEn: ["Wachiraphon", "Phatthanaphanit"],
    team: "Trainee",
    birthday: "1998-12-3",
    province: "Chaiyaphum",
    favorite: ["Banana with Coconut Milk", "Trees have been growed"],
    hobby: [
      "Singing",
      "Watching Series",
      "Watering the plants",
      "Making Flowerpot",
    ],
    img: "https://www.bnk48.com/data/Members/78/pro/l/20200809061404jouwz6.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=78",
    follow: [
      "//www.facebook.com/bnk48official.earn",
      "//www.instagram.com/earn.bnk48official",
    ],
    graduated: false,
    keyword: ["earn", "Earn", "EARN"],
    gen: 3,
  },
  {
    name: "Earth",
    fullnameTh: ["นภสรณ์", "ศิริปาณี"],
    fullnameEn: ["Napason", "Siripanee"],
    team: "Trainee",
    birthday: "2002-4-22",
    province: "Udon Thani",
    favorite: ["Music", "Singing"],
    hobby: ["Singing", "Listening Music", "Watching Cartoon"],
    img: "https://www.bnk48.com/data/Members/79/pro/l/20200809061709hilt45.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=79",
    follow: [
      "https://www.facebook.com/bnk48official.earth",
      "https://www.instagram.com/earth.bnk48official",
    ],
    graduated: false,
    keyword: ["earth", "Earth", "EARTH"],
    gen: 3,
  },
  {
    name: "Eve",
    fullnameTh: ["อิสรีย์", "ทวีกุลพาณิชย์"],
    fullnameEn: ["Issaree", "Taweegulpanit"],
    team: "Trainee",
    birthday: "2003-1-22",
    province: "Yasothon",
    favorite: ["K-Pop", "One Piece (Anime Series)", "Drinking Juices"],
    hobby: [
      "Watching Movies",
      "Listening Music",
      "Singing",
      "Dancing",
      "Exercise",
      "Cleaning",
    ],
    img: "https://www.bnk48.com/data/Members/80/pro/l/20200809062959abdfrx.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=80",
    follow: [
      "https://www.facebook.com/bnk48official.eve",
      "https://www.instagram.com/eve.bnk48official",
    ],
    graduated: false,
    keyword: ["eve", "Eve", "EVE"],
    gen: 3,
  },
  {
    name: "Fame",
    fullnameTh: ["นันทภัค", "กิตติรัตนวิวัฒน์"],
    fullnameEn: ["Nunthapak", "Kittirattanaviwat"],
    team: "Trainee",
    birthday: "2004-10-15",
    province: "Bangkok",
    favorite: ["K-Pop", "Playing with Dogs"],
    hobby: ["Drinking Pearl Milk Tea", "Dancing", "Playing phone"],
    img: "https://www.bnk48.com/data/Members/81/pro/l/20200809063039bwz134.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=81",
    follow: [
      "https://www.facebook.com/bnk48official.fame",
      "https://www.instagram.com/fame.bnk48official",
    ],
    graduated: false,
    keyword: ["fame", "Fame", "FAME"],
    gen: 3,
  },
  {
    name: "Fond",
    fullnameTh: ["ณัฐทิชา", "จันทรวารีเลขา"],
    fullnameEn: ["Natticha", "Chantaravareelekha"],
    team: "NV",
    birthday: "2002-12-3",
    province: "Prachuap Khiri Khan",
    favorite: [
      "Spicy Foods",
      "Pastel tones Stationary",
      "Corgi Dogs",
      "Horror Movies",
    ],
    hobby: ["Dancing", "Cartoon Dubbing", "Watching Movies", "Singing"],
    img: "https://www.bnk48.com/data/Members/46/pro/l/20210602060332nqxy37.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=46",
    follow: [
      "https://www.facebook.com/bnk48official.fond",
      "https://www.instagram.com/fond.bnk48office",
    ],
    graduated: false,
    keyword: ["fond", "Fond", "FOND"],
    gen: 2,
  },
  {
    name: "Grace",
    fullnameTh: ["วิรัลพัชร", "ธำรงค์พันธวนิช"],
    fullnameEn: ["Virunpat", "Thamrongpantavanich"],
    team: "Trainee",
    birthday: "2003-8-2",
    province: "Bangkok",
    favorite: [
      "Dumbo Dolls",
      "Dessert",
      "Ice-cream",
      "Clothes",
      "Dogs",
      "Cats",
      "Take a photoes",
    ],
    hobby: ["Dancing (Ballet, Jazz, Comtemporary)", "Watching Movies"],
    img: "https://www.bnk48.com/data/Members/82/pro/l/20200809063112aenr24.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=82",
    follow: [
      "https://www.facebook.com/bnk48official.grace",
      "https://www.instagram.com/fond.bnk48official",
    ],
    graduated: false,
    keyword: ["grace", "Grace", "GRACE"],
    gen: 3,
  },
  {
    name: "Gygee",
    fullnameTh: ["ณัฐกุล", "พิมพ์ธงชัยกุล"],
    fullnameEn: ["Nuttakul", "Pimtongchaikul"],
    team: "NV",
    birthday: "2001-10-4",
    province: "Bangkok",
    favorite: ["Unicon Dolls", "Cats"],
    hobby: [
      "Reading Comics",
      "Watching Series",
      "Playing Badminton",
      "Singing",
    ],
    img: "https://www.bnk48.com/data/Members/45/pro/l/20210602060352inr578.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=45",
    follow: [
      "https://www.facebook.com/bnk48official.gygee",
      "https://www.instagram.com/gygee.bnk48official",
    ],
    graduated: false,
    keyword: ["gygee", "Gygee", "GYGEE"],
    gen: 2,
  },
  {
    name: "Hoop",
    fullnameTh: ["ปาฏลี", "ประเสริฐธีระชัย"],
    fullnameEn: ["Patalee", "Prasertteerachai"],
    team: "Trainee",
    birthday: "2002-9-18",
    province: "Chonburi",
    favorite: ["Drawing", "Cats", "Eating", "Running"],
    hobby: ["Car Drift", "Take a Photoes", "Finding new Food passion"],
    img: "https://www.bnk48.com/data/Members/83/pro/l/20200809063147aij347.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=83",
    follow: [
      "https://www.facebook.com/bnk48official.hoop",
      "https://www.instagram.com/hoop.bnk48official",
    ],
    graduated: false,
    keyword: ["hoop", "Hoop", "HOOP"],
    gen: 3,
  },
  {
    name: "Jaa",
    fullnameTh: ["ณปภัช", "วรพฤทธานนท์"],
    fullnameEn: ["Napaphat", "Worraphuttanon"],
    team: "NV",
    birthday: "2003-1-20",
    province: "Bangkok",
    favorite: ["Cats", "Roted Clothes", "Bolster Cushion"],
    hobby: ["Listening Music", "Playing Flute", "Watching Movies"],
    img: "https://www.bnk48.com/data/Members/23/pro/l/20210602060416efqtv7.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=23",
    follow: [
      "https://www.facebook.com/bnk48official.jaa",
      "https://www.instagram.com/jaa.bnk48official",
    ],
    graduated: false,
    keyword: ["jaa", "Jaa", "JAA"],
    gen: 1,
  },
  {
    name: "Jane",
    fullnameTh: ["กุลจิราณัฐ", "อินทรศิลป์"],
    fullnameEn: ["Kunjiranut", "Intarasin"],
    team: "BIII",
    birthday: "2000-3-23",
    province: "Pathum Thani",
    favorite: ["Babie's Dolls", "Cats & Dogs", "Hamsters", "Rabbits"],
    hobby: ["Sleeping", "Eating", "Watching Anime"],
    img: "https://www.bnk48.com/data/Members/24/pro/l/20210602060437fhkqz1.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=24",
    follow: [
      "https://www.facebook.com/bnk48official.jane",
      "https://www.instagram.com/jane.bnk48official",
    ],
    graduated: false,
    keyword: ["jane", "Jane", "JANE"],
    gen: 1,
  },
  {
    name: "Jaokhem",
    fullnameTh: ["ชนิกานต์", "บุษดี"],
    fullnameEn: ["Chanikhan", "Busadee"],
    team: "Trainee",
    birthday: "2003-10-12",
    province: "Bangkok",
    favorite: [
      "Panda",
      "Cats & Dogs",
      "Makeup",
      "Chocolates",
      "Take a photoes",
    ],
    hobby: [
      "Playing Ukulele",
      "Drawing",
      "Listening Music",
      "Watching Movies",
      "Traveling",
      "Cooking Dessert",
    ],
    img: "https://www.bnk48.com/data/Members/84/pro/l/20200809063219abmv49.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=84",
    follow: [
      "https://www.facebook.com/bnk48official.jaokhem",
      "https://www.instagram.com/jaokhem.bnk48official",
    ],
    graduated: false,
    keyword: ["jaokhem", "Jaokhem", "JAOKHEM"],
    gen: 3,
  },
  {
    name: "Jennis",
    fullnameTh: ["เจนนิษฐ์", "โอ่ประเสริฐ"],
    fullnameEn: ["Jennis", "Oprasert"],
    team: "BIII",
    birthday: "2000-7-4",
    province: "Petchaburi",
    favorite: [
      "K-Pop (Produce 101)",
      "Weapon Toy Models (Gundum etc.)",
      "Cosmetics",
    ],
    hobby: [
      "Playing Sports",
      "Watching Movies",
      "Listening Music",
      "Watching Anime",
    ],
    img: "https://www.bnk48.com/data/Members/2/pro/l/20210602060501deo589.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=2",
    follow: [
      "https://www.facebook.com/bnk48official.jennis",
      "https://www.instagram.com/jennis.bnk48official",
    ],
    graduated: false,
    keyword: ["jennis", "Jennis", "JENNIS"],
    gen: 1,
  },
  {
    name: "Jib",
    fullnameTh: ["สุชญา", "แสนโคต"],
    fullnameEn: ["Suchaya", "Saenkhot"],
    team: "BIII",
    birthday: "2002-7-4",
    province: "Lopburi",
    favorite: ["Anime", "Guchi"],
    hobby: ["Playing Game", "Drawing", "Listening Music", "Watching Anime"],
    img: "https://www.bnk48.com/data/Members/22/pro/l/20210602060519eklswz.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=22",
    follow: [
      "https://www.facebook.com/bnk48official.jib",
      "https://www.instagram.com/jib.bnk48office",
    ],
    graduated: false,
    keyword: ["jib", "Jib", "JIB"],
    gen: 1,
  },
  {
    name: "Kaew",
    fullnameTh: ["ณัฐรุจา", "ชุติวรรณโสภณ"],
    fullnameEn: ["Natruja", "Chutiwansopon"],
    team: "BIII",
    birthday: "1994-3-31",
    province: "Chonburi",
    favorite: ["Cosmetics", "Perfume"],
    hobby: ["Playing Piano", "Sleeping", "Chill Walking"],
    img: "https://www.bnk48.com/data/Members/21/pro/l/20210602060536fhkop3.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=21",
    follow: [
      "https://www.facebook.com/bnk48official.kaew",
      "https://www.instagram.com/kaew.bnk48official",
    ],
    graduated: false,
    keyword: ["kaew", "Kaew", "KAEW"],
    gen: 1,
  },
  {
    name: "Kaimook",
    fullnameTh: ["วรัทยา", "ดีสมเลิศ"],
    fullnameEn: ["Warattaya", "Deesomlert"],
    team: "NV",
    birthday: "1997-8-27",
    province: "Bangkok",
    favorite: ["Cats"],
    hobby: ["Cooking", "Sewing"],
    img: "https://www.bnk48.com/data/Members/20/pro/l/20210602060552dhmvz2.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=20",
    follow: [
      "https://www.facebook.com/bnk48official.kaimook",
      "https://www.instagram.com/kaimook.bnk48official",
    ],
    graduated: false,
    keyword: ["kaimook", "Kaimook", "KAIMOOK"],
    gen: 1,
  },
  {
    name: "Kaofrang",
    fullnameTh: ["ญาณิศา", "เมืองคำ"],
    fullnameEn: ["Yanisa", "Muangkam"],
    team: "Trainee",
    birthday: "2002-11-15",
    province: "Bangkok",
    favorite: [
      "Fried Meat Salad",
      "Princess",
      "The Sky",
      "Shoping at Market",
      "Everything are pink",
      "Horror Movies",
    ],
    hobby: [
      "Watching Movies",
      "Watching Series",
      "Playing Ukulele",
      "Playing Guitar",
      "Playing Online Game",
    ],
    img: "https://www.bnk48.com/data/Members/86/pro/l/20200809063330hqsv49.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=86",
    follow: [
      "https://www.facebook.com/bnk48official.kaofrang",
      "https://www.instagram.com/kaofrang.bnk48official",
    ],
    graduated: false,
    keyword: ["kaofrang", "Kaofrang", "KAOFRANG"],
    gen: 3,
  },
  {
    name: "Kate",
    fullnameTh: ["กรภัทร์", "นิลประภา"],
    fullnameEn: ["Korapat", "Nilprapa"],
    team: "BIII",
    birthday: "2001-6-9",
    province: "Phayao",
    favorite: ["Gudetama", "Dolls"],
    hobby: ["Relaxing"],
    img: "https://www.bnk48.com/data/Members/19/pro/l/20210602060613knors1.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=19",
    follow: [
      "https://www.facebook.com/bnk48official.kate",
      "https://www.instagram.com/kate.bnk48official",
    ],
    graduated: false,
    keyword: ["kate", "Kate", "KATE"],
    gen: 1,
  },
  {
    name: "Khamin",
    fullnameTh: ["มณิภา", "รู้ปัญญา"],
    fullnameEn: ["Manipa", "Roopanya"],
    team: "Trainee",
    birthday: "1999-4-23",
    province: "Khon Kaen",
    favorite: ["Dogs"],
    hobby: ["Listening Music", "Reading Book"],
    img: "https://www.bnk48.com/data/Members/43/pro/l/20210602060633cmqsw7.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=43",
    follow: [
      "https://www.facebook.com/bnk48official.khamin",
      "https://www.instagram.com/khamin.bnk48official",
    ],
    graduated: false,
    keyword: ["khamin", "Khamin", "KHAMIN"],
    gen: 2,
  },
  {
    name: "Korn",
    fullnameTh: ["วฑูศิริ", "ภูวปัญญาสิริ"],
    fullnameEn: ["Vathusiri", "Phuwapunyasiri"],
    team: "BIII",
    birthday: "1999-1-21",
    province: "Bangkok",
    favorite: ["Kitty"],
    hobby: ["Horror Movies and Books"],
    img: "https://www.bnk48.com/data/Members/18/pro/l/20210602060652aors49.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=18",
    follow: [
      "https://www.facebook.com/bnk48official.korn",
      "https://www.instagram.com/korn.bnk48official",
    ],
    graduated: false,
    keyword: ["korn", "Korn", "KORN"],
    gen: 1,
  },
  {
    name: "Mean",
    fullnameTh: ["ณัฐธันยา", "ดุลยพล"],
    fullnameEn: ["Nathanya", "Dulyapol"],
    team: "Trainee",
    birthday: "2007-7-8",
    province: "Chiangmai",
    favorite: ["Learning new things", "Stickers", "Notebook designing"],
    hobby: ["Singing", "Dancing", "Playing Sport", "Drawing"],
    img: "https://www.bnk48.com/data/Members/87/pro/l/20200809063440dhlrz5.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=87",
    follow: [
      "https://www.facebook.com/bnk48official.mean",
      "https://www.instagram.com/mean.bnk48office",
    ],
    graduated: false,
    keyword: ["mean", "Mean", "MEAN"],
    gen: 3,
  },
  {
    name: "Mind",
    fullnameTh: ["ปณิศา", "ศรีละเลิง"],
    fullnameEn: ["Panisa", "Srilaloeng"],
    team: "Trainee",
    birthday: "2001-9-6",
    province: "Nakhon Ratchasima",
    favorite: ["Rabbits"],
    hobby: ["Listening Japanese Songs (Scandal)"],
    img: "https://www.bnk48.com/data/Members/16/pro/l/20210602060737jkno35.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=16",
    follow: [
      "https://www.facebook.com/bnk48official.mind",
      "https://www.instagram.com/mind.bnk48official",
    ],
    graduated: false,
    keyword: ["mind", "Mind", "MIND"],
    gen: 1,
  },
  {
    name: "Minmin",
    fullnameTh: ["รชยา", "ทัพพ์คุณานนต์"],
    fullnameEn: ["Rachaya", "Tupkunanon"],
    team: "BIII",
    birthday: "1997-3-20",
    province: "Bangkok",
    favorite: ["Papaya Salad"],
    hobby: ["Watching Movies", "Listening Music", "Playing Game"],
    img: "https://www.bnk48.com/data/Members/39/pro/l/20210602060756bfst35.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=39",
    follow: [
      "https://www.facebook.com/bnk48official.minmin",
      "https://www.instagram.com/minmin.bnk48office",
    ],
    graduated: false,
    keyword: ["minmin", "Minmin", "MINMIN"],
    gen: 2,
  },
  {
    name: "Miori",
    fullnameTh: ["มิโอริ", "โอคุโบะ"],
    fullnameEn: ["Miori", "Ohkubo"],
    team: "BIII",
    birthday: "1998-9-30",
    province: "Ibaraki, Japan",
    favorite: ["Sanrio", "Disney", "Morning Musume"],
    hobby: ["Singing"],
    img: "https://www.bnk48.com/data/Members/15/pro/l/20210602060815bes479.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=15",
    follow: [
      "https://www.facebook.com/bnk48official.miori",
      "https://www.instagram.com/miori.bnk48official",
    ],
    graduated: false,
    keyword: ["miori", "Miori", "MIORI"],
    gen: 1,
  },
  {
    name: "Mobile",
    fullnameTh: ["พิมรภัส", "ผดุงวัฒนะโชค"],
    fullnameEn: ["Pimrapat", "Phadungwatanachok"],
    team: "NV",
    birthday: "2002-7-9",
    province: "Bangkok",
    favorite: ["Anime", "Makeup"],
    hobby: ["Cosplay"],
    img: "https://www.bnk48.com/data/Members/14/pro/l/20210602060837kmnst7.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=14",
    follow: [
      "https://www.facebook.com/bnk48official.mobile",
      "https://www.instagram.com/mobile.bnk48official",
    ],
    graduated: false,
    keyword: ["mobile", "Mobile", "MOBILE"],
    gen: 1,
  },
  {
    name: "Monet",
    fullnameTh: ["ภาริตา", "ริเริ่มกุล"],
    fullnameEn: ["Parita", "Rirermkul"],
    team: "Trainee",
    birthday: "2008-8-4",
    province: "Bangkok",
    favorite: [
      "Salmon",
      "Stationary",
      "Camera",
      "Clothes",
      "Shoping at Antique Shop",
    ],
    hobby: ["Dancing", "Feeding the fish", "Funning with Pets"],
    img: "https://www.bnk48.com/data/Members/88/pro/l/20200809063524imyz34.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=88",
    follow: [
      "https://www.facebook.com/bnk48official.monet",
      "https://www.instagram.com/monet.bnk48official",
    ],
    graduated: false,
    keyword: ["monet", "Monet", "MONET"],
    gen: 3,
  },
  {
    name: "Music",
    fullnameTh: ["แพรวา", "สุธรรมพงษ์"],
    fullnameEn: ["Praewa", "Suthamphong"],
    team: "NV",
    birthday: "2001-2-24",
    province: "Bangkok",
    favorite: ["Everything are soft"],
    hobby: ["Cosplay", "Playing Game"],
    img: "https://www.bnk48.com/data/Members/13/pro/l/20210602060900bnx349.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=13",
    follow: [
      "https://www.facebook.com/bnk48official.music",
      "https://www.instagram.com/music.bnk48official",
    ],
    graduated: false,
    keyword: ["music", "Music", "MUSIC"],
    gen: 1,
  },
  {
    name: "Myyu",
    fullnameTh: ["กวิสรา", "สิงห์ปลอด"],
    fullnameEn: ["Khawisara", "Singplod"],
    team: "BIII",
    birthday: "1999-10-28",
    province: "Bangkok",
    favorite: ["Eating Fried Chicken", "Desserts"],
    hobby: ["Watching & Cover Dance from Youtube", "Watching Cook Contents"],
    img: "https://www.bnk48.com/data/Members/38/pro/l/20210602060923giny14.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=38",
    follow: [
      "https://www.facebook.com/bnk48official.myyu",
      "https://www.instagram.com/myyu.bnk48official",
    ],
    graduated: false,
    keyword: ["myyu", "Myyu", "MYYU"],
    gen: 2,
  },
  {
    name: "Namneung",
    fullnameTh: ["มิลิน", "ดอกเทียน"],
    fullnameEn: ["Milin", "Dokthian"],
    team: "NV",
    birthday: "1996-11-11",
    province: "Sing Buri",
    favorite: ["Clothes", "Cosmetics", "Comic Book", "Novel"],
    hobby: ["Sleeping", "Reading Novel", "Listening Music"],
    img: "https://www.bnk48.com/data/Members/12/pro/l/20210602060943nuy357.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=12",
    follow: [
      "https://www.facebook.com/bnk48official.namneung",
      "https://www.instagram.com/namneung.bnk48official",
    ],
    graduated: false,
    keyword: ["namneung", "Namneung", "NAMNEUNG"],
    gen: 1,
  },
  {
    name: "Namsai",
    fullnameTh: ["พิชญาภา", "นาถา"],
    fullnameEn: ["Pichayapa", "Natha"],
    team: "NV",
    birthday: "1999-10-26",
    province: "Chiangmai",
    favorite: ["Alphaca", "Space", "Like Ball's Sports"],
    hobby: ["Eating"],
    img: "https://www.bnk48.com/data/Members/11/pro/l/20210602061005delz47.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=11",
    follow: [
      "https://www.facebook.com/bnk48official.namsai",
      "https://www.instagram.com/namsai.bnk48official",
    ],
    graduated: false,
    keyword: ["namsai", "Namsai", "NAMSAI"],
    gen: 1,
  },
  {
    name: "New",
    fullnameTh: ["ชัญญาภัค", "นุ่มประสพ"],
    fullnameEn: ["Chanyapuk", "Numprasop"],
    team: "NV",
    birthday: "2003-1-2",
    province: "Bangkok",
    favorite: ["Dogs"],
    hobby: ["Listening Music", "Playing Guitar & Piano"],
    img: "https://www.bnk48.com/data/Members/36/pro/l/20210602061029fknrty.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=36",
    follow: [
      "https://www.facebook.com/bnk48official.new",
      "https://www.instagram.com/new.bnk48official",
    ],
    graduated: false,
    keyword: ["new", "New", "NEW"],
    gen: 2,
  },
  {
    name: "Niky",
    fullnameTh: ["วรินท์รัตน์", "ยลประสงค์"],
    fullnameEn: ["Warinrat", "Yolprasong"],
    team: "BIII",
    birthday: "2005-1-26",
    province: "Chiangmai",
    favorite: ["Earring", "Everything are babypink", "Manila Tamarind"],
    hobby: ["Listening Music", "Exercise"],
    img: "https://www.bnk48.com/data/Members/35/pro/l/20210602061052bcgjn8.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=35",
    follow: [
      "https://www.facebook.com/bnk48official.niky",
      "https://www.instagram.com/niky.bnk48office",
    ],
    graduated: false,
    keyword: ["niky", "Niky", "NIKY"],
    gen: 2,
  },
  {
    name: "Nine",
    fullnameTh: ["ภัทรนรินทร์", "เหมือนฤทธิ์"],
    fullnameEn: ["Phattharanarin", "Mueanrit"],
    team: "NV",
    birthday: "2000-1-26",
    province: "Nakhon Sawan",
    favorite: ["Kumamon"],
    hobby: ["Playing Guitar", "Reading Comics"],
    img: "https://www.bnk48.com/data/Members/34/pro/l/20210602061114biky69.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=34",
    follow: [
      "https://www.facebook.com/bnk48official.nine",
      "https://www.instagram.com/nine.bnk48official",
    ],
    graduated: false,
    keyword: ["nine", "Nine", "NINE"],
    gen: 2,
  },
  {
    name: "Noey",
    fullnameTh: ["กานต์ธีรา", "วัชรทัศนกุล"],
    fullnameEn: ["Kanteera", "Wadcharathadsanakul"],
    team: "BIII",
    birthday: "1997-4-9",
    province: "Samut Prakan",
    favorite: ["Cosmetics", "Watch", "Luxury Bags"],
    hobby: ["Sleeping"],
    img: "https://www.bnk48.com/data/Members/9/pro/l/20210602061134ilpvxz.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=9",
    follow: [
      "https://www.facebook.com/bnk48official.noey",
      "https://www.instagram.com/noey.bnk48office",
    ],
    graduated: false,
    keyword: ["noey", "Noey", "NOEY"],
    gen: 1,
  },
  {
    name: "Orn",
    fullnameTh: ["พัศชนันท์", "เจียจิรโชติ"],
    fullnameEn: ["Patchanan", "Jiajirachote"],
    team: "NV",
    birthday: "1997-2-3",
    province: "Bangkok",
    favorite: ["Cats", "Seals", "Fashion", "Cosmetics"],
    hobby: ["Sleeping", "Reading Book", "Playing with Cat"],
    img: "https://www.bnk48.com/data/Members/3/pro/l/20210602061157ceg369.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=3",
    follow: [
      "https://www.facebook.com/bnk48official.orn",
      "https://www.instagram.com/orn.bnk48official",
    ],
    graduated: false,
    keyword: ["orn", "Orn", "ORN"],
    gen: 1,
  },
  {
    name: "Paeyah",
    fullnameTh: ["นิพพิชฌาน์", "พิพิธเดชา"],
    fullnameEn: ["Nippitcha", "Pipitdaecha"],
    team: "Trainee",
    birthday: "2005-5-14",
    province: "Bangkok",
    favorite: ["Strawberry", "Dinosaur", "Cosmetics"],
    hobby: ["Cover Dance", "Watching Series", "Listening Music"],
    img: "https://www.bnk48.com/data/Members/89/pro/l/20200809063705fglt79.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=89",
    follow: [
      "https://www.facebook.com/bnk48official.paeyah",
      "https://www.instagram.com/paeyah.bnk48official",
    ],
    graduated: false,
    keyword: ["paeyah", "Paeyah", "PAEYAH"],
    gen: 3,
  },
  {
    name: "Pakwan",
    fullnameTh: ["พาขวัญ", "น้อยใจบุญ"],
    fullnameEn: ["Pakwan", "Noijaiboon"],
    team: "Trainee",
    birthday: "2000-2-18",
    province: "Sakon Nakhon",
    favorite: [
      "All animals except reptile",
      "Ice-cream",
      "Everything are pink",
      "Take a photoes",
      "Dolls",
      "Get dressed",
      "Be Curious",
    ],
    hobby: [
      "Singing, Listening and producing songs",
      "Playing musical instrument (Violin, Ukulele, Guitar, Piano, Dulcimer - Postscript from her 'I can play but not well hahaha')",
      "Playing Sport (Basketball, Yoga, Thai Boxing, Playing with dogs)",
      "Cleaning room/House",
      "Drawing",
      "Grow a plants",
    ],
    img: "https://www.bnk48.com/data/Members/32/pro/l/20210602061220bdmr38.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=32",
    follow: [
      "https://www.facebook.com/bnk48official.pakwan",
      "https://www.instagram.com/pakwan.bnk48official",
    ],
    graduated: false,
    keyword: ["pakwan", "Pakwan", "PAKWAN"],
    gen: 2,
  },
  {
    name: "Pampam",
    fullnameTh: ["สาริศา", "วรสุนทร"],
    fullnameEn: ["Sarisa", "Worasunthorn"],
    team: "Trainee",
    birthday: "2003-7-3",
    province: "Nakorn Ratchasima",
    favorite: [
      "Cats",
      "Creyon Shinchan (Manga Series)",
      "Everything are pink",
      "Dolls",
      "Cafe",
      "Tulip",
    ],
    hobby: [
      "Watching Series",
      "Watching Movies",
      "Take a Photoes",
      "Traveling",
    ],
    img: "https://www.bnk48.com/data/Members/90/pro/l/20200809063802bpuy15.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=90",
    follow: [
      "https://www.facebook.com/bnk48official.pampam",
      "https://www.instagram.com/pampam.bnk48official",
    ],
    graduated: false,
    keyword: ["pampam", "Pampam", "PAMPAM"],
    gen: 3,
  },
  {
    name: "Pancake",
    fullnameTh: ["พิทยาภรณ์", "เกียรติฐิตินันท์"],
    fullnameEn: ["Pitthayaporn", "Kiatthitinan"],
    team: "Trainee",
    birthday: "2007-2-6",
    province: "Bangkok",
    favorite: [
      "Stitch (Walt Disney's Cartoon chracter)",
      "Games",
      "Accessories",
      "Dolls",
    ],
    hobby: [
      "Watching Movies",
      "Take a Photoes",
      "Playing Games",
      "Listening Music",
    ],
    img: "https://www.bnk48.com/data/Members/91/pro/l/20200809063832fhktu8.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=91",
    follow: [
      "https://www.facebook.com/bnk48official.pancake",
      "https://www.instagram.com/pancake.bnk48official",
    ],
    graduated: false,
    keyword: ["pancake", "Pancake", "PANCAKE"],
    gen: 3,
  },
  {
    name: "Panda",
    fullnameTh: ["จิดาภา", "แช่มช้อย"],
    fullnameEn: ["Jidarpha", "Chamchooy"],
    team: "BIII",
    birthday: "1997-10-10",
    province: "Nakhon Pathom",
    favorite: ["Dumbo Rat", "Chocolates", "Singing"],
    hobby: ["Reading Book", "Watching Movie", "Drawing"],
    img: "https://www.bnk48.com/data/Members/31/pro/l/20210602061244bcjnq5.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=31",
    follow: [
      "https://www.facebook.com/bnk48official.panda",
      "https://www.instagram.com/panda.bnk48official",
    ],
    graduated: false,
    keyword: ["panda", "Panda", "PANDA"],
    gen: 2,
  },
  {
    name: "Peak",
    fullnameTh: ["ภูษิตา", "วัฒนากรแก้ว"],
    fullnameEn: ["Phusita", "Watthanakronkeaw"],
    team: "Trainee",
    birthday: "2004-4-2",
    province: "Samut Prakan",
    favorite: ["Vintage Clothes", "Postcard", "Milk Tea"],
    hobby: ["Listening Music", "Cover Dance", "Drawing", "Get dressed"],
    img: "https://www.bnk48.com/data/Members/92/pro/l/20200809063901lmpu46.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=92",
    follow: [
      "https://www.facebook.com/bnk48official.peak",
      "https://www.instagram.com/peak.bnk48official",
    ],
    graduated: false,
    keyword: ["peak", "Peak", "PEAK"],
    gen: 3,
  },
  {
    name: "Phukkhom",
    fullnameTh: ["สิริการย์", "ชินวัชร์สุวรรณ"],
    fullnameEn: ["Sirikarn", "Shinnawatsuwan"],
    team: "NV",
    birthday: "1998-2-28",
    province: "Samut Prakan",
    favorite: ["Japanese Dolls", "Ghost Story", "Princess"],
    hobby: ["Singing", "Watching Movie", "Drawing", "D.I.Y job"],
    img: "https://www.bnk48.com/data/Members/30/pro/l/20210602061306abpqu9.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=30",
    follow: [
      "https://www.facebook.com/bnk48official.phukkhom",
      "https://www.instagram.com/phukkhom.bnk48official",
    ],
    graduated: false,
    keyword: ["phukkhom", "Phukkhom", "PHUKKHOM"],
    gen: 2,
  },
  {
    name: "Piam",
    fullnameTh: ["รินรดา", "อินทร์ไธสง"],
    fullnameEn: ["Rinrada", "Inthaisong"],
    team: "BIII",
    birthday: "2003-6-4",
    province: "Saraburi",
    favorite: ["Corgi Dogs", "Gundum", "Figure"],
    hobby: ["Sleeping", "Eating", "Playing Games"],
    img: "https://www.bnk48.com/data/Members/8/pro/l/20210602061332hsu257.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=8",
    follow: [
      "https://www.facebook.com/bnk48official.piam",
      "https://www.instagram.com/piam.bnk48official",
    ],
    graduated: false,
    keyword: ["piam", "Piam", "PIAM"],
    gen: 1,
  },
  {
    name: "Pim",
    fullnameTh: ["ณิชารีย์", "วชิรลาภไพฑูรย์"],
    fullnameEn: ["Nicharee", "Wachiralapphaithoon"],
    team: "Trainee",
    birthday: "2006-2-26",
    province: "Bangkok",
    favorite: [
      "Dolls",
      "Cats",
      "Everything are pink",
      "Cookies",
      "Chocolates",
      "Common Daisy",
    ],
    hobby: ["Listening Music", "Reading Book", "Take a Photoes"],
    img: "https://www.bnk48.com/data/Members/93/pro/l/20200809063927abdemy.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=93",
    follow: [
      "https://www.facebook.com/bnk48official.pim",
      "https://www.instagram.com/pim.bnk48official",
    ],
    graduated: false,
    keyword: ["pim", "Pim", "PIM"],
    gen: 3,
  },
  {
    name: "Popper",
    fullnameTh: ["พิณญาดา", "จึงกาญจนา"],
    fullnameEn: ["Pinyada", "Jungkanjana"],
    team: "Trainee",
    birthday: "1998-9-13",
    province: "Ubom Ratchathani",
    favorite: [
      "Dogs & Cats",
      "Foods",
      "Novels",
      "Movies",
      "Literature",
      "Artwork Style",
    ],
    hobby: [
      "Watching Movies",
      "Reading Book",
      "Seeing Artwork Style",
      "Take a photoes",
    ],
    img: "https://www.bnk48.com/data/Members/94/pro/l/20200809063958fhqvwx.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=94",
    follow: [
      "https://www.facebook.com/bnk48official.popper",
      "https://www.instagram.com/popper.bnk48official",
    ],
    graduated: false,
    keyword: ["popper", "Popper", "POPPER"],
    gen: 3,
  },
  {
    name: "Pun",
    fullnameTh: ["ปัญสิกรณ์", "ติยะกร"],
    fullnameEn: ["Punsikorn", "Tiyakorn"],
    team: "BIII",
    birthday: "2000-11-9",
    province: "Bangkok",
    favorite: ["Fashion"],
    hobby: ["Listening Music", "Playing phone"],
    img: "https://www.bnk48.com/data/Members/1/pro/l/20210602061355blpq29.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=1",
    follow: [
      "https://www.facebook.com/bnk48official.pun",
      "https://www.instagram.com/pun.bnk48official",
    ],
    graduated: false,
    keyword: ["pun", "Pun", "PUN"],
    gen: 1,
  },
  {
    name: "Pupe",
    fullnameTh: ["จิรดาภา", "อินทจักร"],
    fullnameEn: ["Jiradapa", "Intajak"],
    team: "NV",
    birthday: "1998-1-18",
    province: "Chiangrai",
    favorite: ["Blanket", "Everything are pink", "Doraemon (Manga Series)"],
    hobby: ["Listening Music", "Playing game", "Watching Anime", "Sleeping"],
    img: "https://www.bnk48.com/data/Members/7/pro/l/20210602061415afm567.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=7",
    follow: [
      "https://www.facebook.com/bnk48official.pupe",
      "https://www.instagram.com/pupe.bnk48official",
    ],
    graduated: false,
    keyword: ["pupe", "Pupe", "PUPE"],
    gen: 1,
  },
  {
    name: "Ratah",
    fullnameTh: ["รตา", "ชินกระจ่างกิจ"],
    fullnameEn: ["Ratah", "Chinkrajangkit"],
    team: "Trainee",
    birthday: "2002-3-27",
    province: "Chiangmai",
    favorite: ["Cats", "Everything are yellow", "Eating"],
    hobby: ["Producing Novels", "Cover Dance"],
    img: "https://www.bnk48.com/data/Members/29/pro/l/20210602061436ahlt29.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=29",
    follow: [
      "https://www.facebook.com/bnk48official.ratah",
      "https://www.instagram.com/ratah.bnk48official",
    ],
    graduated: false,
    keyword: ["ratah", "Ratah", "RATAH"],
    gen: 2,
  },
  {
    name: "Satchan",
    fullnameTh: ["สวิชญา", "ขจรรุ่งศิลป์"],
    fullnameEn: ["Sawitchaya", "Kajonrungsilp"],
    team: "NV",
    birthday: "2003-12-13",
    province: "Bangkok",
    favorite: ["Singing"],
    hobby: ["Listening Music"],
    img: "https://www.bnk48.com/data/Members/6/pro/l/20210602061457fmoq17.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=6",
    follow: [
      "https://www.facebook.com/bnk48official.satchan",
      "https://www.instagram.com/satchan.bnk48official",
    ],
    graduated: false,
    keyword: ["satchan", "Satchan", "SATCHAN"],
    gen: 1,
  },
  {
    name: "Stang",
    fullnameTh: ["ตริษา", "ปรีชาตั้งกิจ"],
    fullnameEn: ["Tarisa", "Preechatangkit"],
    team: "NV",
    birthday: "2003-10-22",
    province: "Bangkok",
    favorite: ["Omlet"],
    hobby: ["Playing Guitar"],
    img: "https://www.bnk48.com/data/Members/28/pro/l/20210602061520hmry48.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=28",
    follow: [
      "https://www.facebook.com/bnk48official.stang",
      "https://www.instagram.com/stang.bnk48official",
    ],
    graduated: false,
    keyword: ["stang", "Stang", "STANG"],
    gen: 2,
  },
  {
    name: "Tarwaan",
    fullnameTh: ["อิสราภา", "ธวัชภักดี"],
    fullnameEn: ["Isarapa", "Thawatpakdee"],
    team: "NV",
    birthday: "1996-12-18",
    province: "Nakhon Pathom",
    favorite: [],
    hobby: ["Watching Movies", "Listening Music"],
    img: "https://www.bnk48.com/data/Members/5/pro/l/20210602061540ghtuy2.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=5",
    follow: [
      "https://www.facebook.com/bnk48official.tarwaan",
      "https://www.instagram.com/tarwaan.bnk48official",
    ],
    graduated: false,
    keyword: ["tarwaan", "Tarwaan", "TARWAAN"],
    gen: 1,
  },
  {
    name: "View",
    fullnameTh: ["กมนธิดา", "โรจน์ทวีนิธิ"],
    fullnameEn: ["Kamonthida", "Rotthawinithi"],
    team: "Trainee",
    birthday: "2004-5-28",
    province: "Nonthaburi",
    favorite: ["Spicy Noodle"],
    hobby: ["Reading Comics", "Listening Music"],
    img: "https://www.bnk48.com/data/Members/27/pro/l/20210602061558ahipx2.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=27",
    follow: [
      "https://www.facebook.com/bnk48official.view",
      "https://www.instagram.com/view.bnk48official",
    ],
    graduated: false,
    keyword: ["view", "View", "VIEW"],
    gen: 2,
  },
  {
    name: "Wee",
    fullnameTh: ["วีรยา", "จาง"],
    fullnameEn: ["Weeraya", "Zhang"],
    team: "BIII",
    birthday: "2001-10-23",
    province: "Chonburi",
    favorite: ["Salad", "Vegetables (Except Celery)"],
    hobby: ["Watching movies", "Swimming", "Playing games"],
    img: "https://bnk48.com/data/Members/26/pro/l/20210602061618dmor89.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=27",
    follow: [
      "https://www.facebook.com/bnk48official.wee",
      "https://www.instagram.com/wee.bnk48official",
    ],
    graduated: false,
    keyword: ["wee", "Wee", "WEE"],
    gen: 2,
  },
  {
    name: "Yayee",
    fullnameTh: ["ณัฏฐธิดา", "อาสนานิ"],
    fullnameEn: ["Natthathida", "Asanani"],
    team: "Trainee",
    birthday: "2001-10-9",
    province: "Nong Khai",
    favorite: [
      "Everything are red",
      "Hip-Hop",
      "About psychology and Feeling sense",
    ],
    hobby: ["Practice Dancing", "Listeming music", "Watching cartoon"],
    img: "https://www.bnk48.com/data/Members/95/pro/l/20200809064027ikry89.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=95",
    follow: [
      "https://www.facebook.com/bnk48official.yayee",
      "https://www.instagram.com/yayee.bnk48official",
    ],
    graduated: false,
    keyword: ["yayee", "Yayee", "YAYEE"],
    gen: 3,
  },
  {
    name: "Yoghurt",
    fullnameTh: ["นพรดา", "เลิศวิริยะพร"],
    fullnameEn: ["Nopparada", "Leartviriyaporn"],
    team: "Trainee",
    birthday: "2004-11-10",
    province: "Bangkok",
    favorite: [
      "Sleeping",
      "Eating",
      "Take a photoes",
      "Watching Movies",
      "Chocolates",
      "Green Tea Daifuku",
      "Film Camera",
      "Space",
    ],
    hobby: [
      "Watching Movies",
      "Listeming music",
      "Cooking dessert",
      "Reading novels",
      "Playing Guitar",
      "Playing Ukulele",
    ],
    img: "https://www.bnk48.com/data/Members/96/pro/l/20200809064057acklv9.png",
    ref: "https://www.bnk48.com/index.php?page=listMembers&memberId=96",
    follow: [
      "https://www.facebook.com/bnk48official.yoghurt",
      "https://www.instagram.com/yoghurt.bnk48official",
    ],
    graduated: false,
    keyword: ["yoghurt", "Yoghurt", "YOGHURT"],
    gen: 3,
  },
];
const menu = [
  {
    id: 1,
    title: "buttermilk pancakes",
    category: "breakfast",
    price: 15.99,
    img: "./images/item-1.jpeg",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: "diner double",
    category: "lunch",
    price: 13.99,
    img: "./images/item-2.jpeg",
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: "godzilla milkshake",
    category: "shakes",
    price: 6.99,
    img: "./images/item-3.jpeg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: "country delight",
    category: "breakfast",
    price: 20.99,
    img: "./images/item-4.jpeg",
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: "egg attack",
    category: "lunch",
    price: 22.99,
    img: "./images/item-5.jpeg",
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: "oreo dream",
    category: "shakes",
    price: 18.99,
    img: "./images/item-6.jpeg",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: "bacon overflow",
    category: "breakfast",
    price: 8.99,
    img: "./images/item-7.jpeg",
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: "american classic",
    category: "lunch",
    price: 12.99,
    img: "./images/item-8.jpeg",
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: "quarantine buddy",
    category: "shakes",
    price: 16.99,
    img: "./images/item-9.jpeg",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];

export default data;
